### ISSUE TITLE
Add Check for Box in Play Area

### ISSUE THREAD

**Issue by ash-anand** [vershwal/Moving-Square-Game#1]
If the down/up arrow is pressed for long enough the box disappears from the play area and the point counter keeps running. 
A check must be put to avoid this behaviour restricting the box in play area or ending the game if the box goes out of bounds.

**Comment by vershwal** [comment]
Fixed here : <https://github.com/vershwal/Moving-Square-Game/commit/db8cb946af17e8c87555266acfa9f1b23a87334e>

**Comment by vershwal** [comment]
Thanks, @ash-anand.
